[env]
WALLET_DIR = "${CARGO_MAKE_WORKING_DIRECTORY}/../example/wallet"
WALLET_MPK = "${CARGO_MAKE_WORKING_DIRECTORY}/../target/wasm32-wasip2/release/wallet.mpk"
TESTING_MPK_DIR = "${CARGO_MAKE_WORKING_DIRECTORY}/mpk"
TESTING_WALLET_MPK = "${TESTING_MPK_DIR}/wallet.mpk"

[tasks.build-wallet-mpk]
command = "cargo"
args = ["make", "package"]
cwd = "${WALLET_DIR}"

[tasks.prepare-mpk-dir]
command = "mkdir"
args = ["-p", "${TESTING_MPK_DIR}"]

[tasks.copy-wallet-mpk]
dependencies = ["build-wallet-mpk", "prepare-mpk-dir"]
command = "cp"
args = ["${WALLET_MPK}", "${TESTING_WALLET_MPK}"]

[tasks.test]
dependencies = ["copy-wallet-mpk"]
command = "cargo"
args = ["test", "-p", "testing", "--", "--nocapture"]

[tasks.default]
alias = "test"
