package mududb:api;

interface system {
    query: func(query-in: list<u8>) -> list<u8>;

    fetch: func(query-result: list<u8>) -> list<u8>;

    command: func(command-in: list<u8>) -> list<u8>;

    batch: func(batch-in:list<u8>) -> list<u8>;

    open: func(open-in: list<u8>) -> list<u8>;

    close: func(close-in: list<u8>) -> list<u8>;

    get: func(get-in: list<u8>) -> list<u8>;

    put: func(put-in: list<u8>) -> list<u8>;

    delete: func(delete-in: list<u8>) -> list<u8>;

    range: func(range-in: list<u8>) -> list<u8>;
}

world api {
    import system;
}
